server:
  port: 8082


spring:
  application:
    name: hotels-service
  datasource:
    url: jdbc:mysql://localhost:3306/hrs
    username: root
    password: Kumar@0852


  jpa:
    hibernate:
        ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/