server:
  port: 8086

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: HOTELS-SERVICE-GATEWAY
          uri: lb://HOTELS-SERVICE
          predicates:
            - Path=/hotels/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



